---

- name: Configuraciones de Firewall (Kubernetes)
  hosts: [master, workers]
  become: true

  tasks:
    
    - name: Configurando el firewall
      ansible.builtin.copy:
        src: ./k8s.conf
        dest: /etc/sysctl.d/k8s.conf 
    
    - name: Aplicando configuración de firewall
      command: sysctl --system
    
