---

- name: Configuración de zonas horarias
  hosts: all
  become: true

  tasks:

    - name: Configurar TimeZone Madrid
      command: timedatectl set-timezone Europe/Madrid

    - name: Instalar chrony
      dnf:
        name: chrony
        state: latest

    - name: Iniciar servicio chronyd en el arranque
      command: systemctl enable chronyd

    - name: Iniciar chronyd
      command: systemctl start chronyd
    
    - name: Habilitar NTP
      command: timedatectl set-ntp true
