---

- name: Configuración del firewall para el acceso de los contendores a localhost
  hosts: [master]
  become: true

  tasks:

    - name: Configurando acceso del worker
      firewalld:
        rich_rule: rule family=ipv4 source address=172.17.0.0/16 accept
        permanent: yes
        state: enabled

    - name: Reload de firewalld
      systemd:
        name: firewalld
        state: reloaded

